const MAX_REQUEST_ALLOWED = 5;
const TIME_IN_SECONDS = 60;
const TIME_MILISECONDS = 1000;
const MAX_IP_SEARCH_LENGHT = 10;

module.exports = {
  TIME_IN_SECONDS,
  TIME_MILISECONDS,
  MAX_IP_SEARCH_LENGHT,
  MAX_REQUEST_ALLOWED,
};
