const MAX_REQUEST_ALLOWED = 5;
const ONE_MIN_TIME_IN_MILLISECONDS = 60 * 1000;
const MAX_IP_SEARCH_LENGHT = 10;

module.exports = {
  MAX_IP_SEARCH_LENGHT,
  ONE_MIN_TIME_IN_MILLISECONDS,
  MAX_REQUEST_ALLOWED,
};
